// src/utils/styles.js

const styles = {
  root: {
    fontFamily: "'Noto Sans JP', 'Helvetica Neue', sans-serif",
    background: "#F7F8FC",
    minHeight: "100vh",
    color: "#1a1a2e",
  },
  header: {
    background: "#1a1a2e",
    padding: "0 16px",
    position: "sticky",
    top: 0,
    zIndex: 100,
    boxShadow: "0 2px 12px rgba(0,0,0,0.18)",
  },
  headerInner: {
    maxWidth: 720,
    margin: "0 auto",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    height: 56,
  },
  logo: { display: "flex", alignItems: "center", gap: 8 },
  logoIcon: { fontSize: 22 },
  logoText: {
    fontSize: 13,
    fontWeight: 700,
    letterSpacing: "0.15em",
    color: "#FF4757",
  },
  nav: { display: "flex", gap: 4 },
  navBtn: {
    background: "transparent",
    border: "none",
    color: "#aaa",
    fontSize: 12,
    fontWeight: 600,
    letterSpacing: "0.08em",
    padding: "6px 12px",
    borderRadius: 6,
    cursor: "pointer",
    transition: "all 0.15s",
  },
  navBtnActive: {
    background: "#FF475718",
    color: "#FF4757",
  },
  main: {
    maxWidth: 720,
    margin: "0 auto",
    padding: "20px 16px 60px",
  },
  page: {},
  heroSection: {
    padding: "5px 0 20px",
  },
  heroTitle: {
    fontSize: 30,
    fontWeight: 900,
    lineHeight: 1.25,
    margin: 0,
    letterSpacing: "-0.02em",
  },
  heroSub: {
    marginTop: 8,
    color: "#888",
    fontSize: 13,
    letterSpacing: "0.05em",
  },
  statsRow: {
    display: "flex",
    alignItems: "center",
    gap: 0,
    background: "#fff",
    borderRadius: 14,
    padding: "16px 24px",
    marginBottom: 24,
    boxShadow: "0 2px 12px rgba(0,0,0,0.06)",
  },
  statCard: { flex: 1, textAlign: "center" },
  statNum: { fontSize: 32, fontWeight: 800, color: "#FF4757", lineHeight: 1 },
  statLabel: {
    fontSize: 11,
    color: "#aaa",
    marginTop: 4,
    letterSpacing: "0.05em",
  },
  statDivider: { fontSize: 24, color: "#e0e0e0", padding: "0 8px" },
  sectionTitle: {
    fontSize: 13,
    fontWeight: 700,
    color: "#888",
    letterSpacing: "0.08em",
    marginBottom: 12,
    textTransform: "uppercase",
  },
  memberGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fill, minmax(150px, 1fr))",
    gap: 10,
  },
  memberCard: {
    background: "#fff",
    borderRadius: 12,
    padding: "12px 10px",
    boxShadow: "0 1px 6px rgba(0,0,0,0.05)",
    border: "2px solid transparent",
    transition: "all 0.2s",
    position: "relative",
  },
  memberCardAttending: {
    border: "2px solid #FF475740",
    background: "#FFF8F8",
  },
  memberCardArrived: {
    border: "2px solid #2ED57340",
    background: "#F5FFFB",
  },
  memberName: {
    fontSize: 13,
    fontWeight: 700,
    marginBottom: 4,
  },
  memberPos: { marginBottom: 8 },
  posBadge: {
    display: "inline-block",
    fontSize: 11,
    fontWeight: 700,
    padding: "2px 8px",
    borderRadius: 20,
  },
  memberBtns: { display: "flex", gap: 4, flexWrap: "wrap" },
  smBtn: {
    fontSize: 11,
    fontWeight: 700,
    border: "none",
    borderRadius: 6,
    padding: "5px 8px",
    cursor: "pointer",
    transition: "all 0.15s",
  },
  teamBadge: {
    position: "absolute",
    top: 8,
    right: 8,
    fontSize: 10,
    fontWeight: 700,
    color: "#fff",
    padding: "2px 7px",
    borderRadius: 20,
  },
  memberListSelect: {
    display: "flex",
    flexDirection: "column",
    gap: 8,
  },
  memberSelectBtn: {
    background: "#fff",
    border: "1px solid #eee",
    borderRadius: 10,
    padding: "14px 16px",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    gap: 8,
    textAlign: "left",
    transition: "all 0.15s",
    fontSize: 14,
    fontWeight: 600,
  },
  memberSelectName: { flex: 1 },
  greenDot: {
    width: 8,
    height: 8,
    background: "#2ED573",
    borderRadius: "50%",
    display: "inline-block",
  },
  personalView: {},
  backBtn: {
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
    background: "#fff",
    border: "1px solid #e8e8e8",
    borderRadius: 10,
    color: "#555",
    cursor: "pointer",
    fontSize: 14,
    fontWeight: 600,
    padding: "10px 16px",
    marginBottom: 20,
    boxShadow: "0 1px 4px rgba(0,0,0,0.06)",
    transition: "all 0.2s ease",
  },
  backBtnIcon: {
    fontSize: 16,
    lineHeight: 1,
    opacity: 0.9,
  },
  /** 戻るボタンの hover/active 用 CSS（className="back-btn" に注入する想定） */
  backBtnHoverCSS: `
    .back-btn:hover {
      background: #f8f8f8;
      border-color: #ddd;
      box-shadow: 0 2px 8px rgba(0,0,0,0.08);
    }
    .back-btn:active {
      transform: scale(0.95);
    }
  `,

  personalCard: {
    background: "#fff",
    borderRadius: 16,
    padding: 24,
    boxShadow: "0 2px 16px rgba(0,0,0,0.07)",
  },
  personalName: {
    fontSize: 24,
    fontWeight: 900,
    marginBottom: 4,
  },
  personalPos: {
    fontSize: 14,
    color: "#888",
    marginBottom: 20,
  },
  personalBtnRow: {
    display: "flex",
    gap: 12,
    marginBottom: 20,
  },
  bigBtn: {
    flex: 1,
    padding: "14px",
    fontSize: 14,
    fontWeight: 700,
    borderRadius: 12,
    cursor: "pointer",
    transition: "all 0.2s",
  },
  myTeamBox: {
    border: "2px solid",
    borderRadius: 12,
    padding: 16,
    textAlign: "center",
  },
  myTeamName: {
    fontSize: 22,
    fontWeight: 900,
  },
  noTeamBox: {
    background: "#f7f7f7",
    borderRadius: 12,
    padding: 16,
    textAlign: "center",
    color: "#aaa",
    fontSize: 13,
  },
  adminCard: {
    background: "#fff",
    borderRadius: 16,
    padding: 20,
    marginBottom: 8,
    boxShadow: "0 2px 12px rgba(0,0,0,0.06)",
  },
  adminRow: {
    display: "flex",
    gap: 24,
    marginBottom: 20,
  },
  adminStat: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
  },
  adminStatNum: {
    fontSize: 36,
    fontWeight: 900,
    color: "#FF4757",
    lineHeight: 1,
  },
  adminStatLabel: {
    fontSize: 11,
    color: "#aaa",
    marginTop: 2,
  },
  teamInputRow: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    marginBottom: 16,
  },
  teamLabel: {
    fontSize: 14,
    fontWeight: 700,
  },
  teamCounter: {
    display: "flex",
    alignItems: "center",
    gap: 1,
    background: "#f5f5f5",
    borderRadius: 10,
  },
  counterBtn: {
    background: "none",
    border: "none",
    fontSize: 18,
    fontWeight: 700,
    cursor: "pointer",
    color: "#555",
    lineHeight: 1,
    padding: "8px 16px",
    borderRadius: 6,
    transition: "background 0.15s, transform 0.15s",
  },
  counterNum: {
    fontSize: 20,
    fontWeight: 900,
    minWidth: 24,
    textAlign: "center",
  },
  perTeam: {
    fontSize: 12,
    color: "#aaa",
  },
  generateBtn: {
    width: "100%",
    background: "#FF4757",
    color: "#fff",
    border: "none",
    borderRadius: 12,
    padding: "14px",
    fontSize: 15,
    fontWeight: 700,
    cursor: "pointer",
    letterSpacing: "0.04em",
    transition: "all 0.2s",
  },
  warnText: {
    fontSize: 12,
    color: "#FF4757",
    marginTop: 8,
    textAlign: "center",
  },
  teamsGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fill, minmax(180px, 1fr))",
    gap: 12,
  },
  teamCard: {
    background: "#fff",
    borderRadius: 14,
    padding: 16,
    boxShadow: "0 2px 12px rgba(0,0,0,0.06)",
  },
  teamCardTitle: {
    fontSize: 15,
    fontWeight: 800,
    marginBottom: 12,
    letterSpacing: "0.02em",
  },
  teamMembers: {
    display: "flex",
    flexDirection: "column",
    gap: 6,
  },
  teamMemberRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
  },
  teamMemberName: {
    fontSize: 13,
    fontWeight: 600,
  },
  teamCount: {
    marginTop: 10,
    fontSize: 11,
    color: "#aaa",
    textAlign: "right",
  },
  tableWrap: {
    overflowX: "auto",
    borderRadius: 12,
    boxShadow: "0 2px 12px rgba(0,0,0,0.06)",
  },
  table: {
    width: "100%",
    borderCollapse: "collapse",
    background: "#fff",
    borderRadius: 12,
    overflow: "hidden",
    fontSize: 13,
  },
  th: {
    background: "#1a1a2e",
    color: "#fff",
    padding: "10px 14px",
    textAlign: "left",
    fontWeight: 700,
    fontSize: 12,
    letterSpacing: "0.06em",
  },
  td: {
    padding: "10px 14px",
    borderBottom: "1px solid #f0f0f0",
  },

  // ===== 練習日の選択UI用に追加したスタイル =====
  practiceSelectRow: {
    display: "flex",
    alignItems: "center",
    gap: "10px",
    marginBottom: "20px",
    background: "#fff",
    padding: "12px 16px",
    borderRadius: "12px",
    boxShadow: "0 2px 8px rgba(0,0,0,0.05)",
  },
  dateInput: {
    padding: "8px 12px",
    borderRadius: "6px",
    border: "1px solid #ccc",
    fontSize: "14px",
  },
  selectBox: {
    padding: "8px 12px",
    borderRadius: "6px",
    border: "1px solid #ccc",
    fontSize: "14px",
    flex: 1,
  },
};

export default styles;
